### ISSUE TITLE
HuggingFace range read error

### ISSUE THREAD

**Issue by rchowell** [Eventual-Inc/Daft#4907]
### Describe the bug

I faced an error when reading from a HuggingFace dataset which killed a long-running query at the very end :sad-cowboy:

```
daft.exceptions.DaftCoreException: DaftError::External Cached error: Unable to open file https://huggingface.co/api/datasets/stanfordnlp/snli/parquet/plain_text/train/0.parquet: reqwest::Error { kind: Status(416, Some(ReasonPhrase(b"Requested Range Not Satisfiable"))), url: "https://huggingface.co/api/datasets/stanfordnlp/snli/parquet/plain_text/train/0.parquet" }
```

### To Reproduce

```python
df = daft.read_parquet("hf://datasets/stanfordnlp/snli/")
df.write_parquet("./out")
```

```
daft.exceptions.DaftCoreException: DaftError::External Cached error: Unable to open file https://huggingface.co/api/datasets/stanfordnlp/snli/parquet/plain_text/train/0.parquet: reqwest::Error { kind: Status(416, Some(ReasonPhrase(b"Requested Range Not Satisfiable"))), url: "https://huggingface.co/api/datasets/stanfordnlp/snli/parquet/plain_text/train/0.parquet" }
```

### Component(s)

Parquet

**Comment by desmondcheongzx** [comment]
Dang that's seriously no bueno. I'll look into it

**Comment by universalmind303** [comment]
@rchowell, are you using the latest version of daft? This should have been fixed in https://github.com/Eventual-Inc/Daft/pull/4853


see https://github.com/Eventual-Inc/Daft/issues/4780.

**Comment by rchowell** [comment]
I'm checked out at https://github.com/Eventual-Inc/Daft/commit/7987455e9d8cbed59f8e1d7bf3ac99a125f7c2ad which includes that commit, but still facing the error. Will try to clearing + rebuiliding.

<img width="626" height="303" alt="Image" src="https://github.com/user-attachments/assets/b119300f-6fe0-466f-94dd-31096459c4e8" />

**Comment by universalmind303** [comment]
am able to reproduce. 

it seems to work if you do `df.show()`, but not `df.collect()`.

**Comment by universalmind303** [comment]
closing in favor of the [original](https://github.com/Eventual-Inc/Daft/issues/4780) that has more context.
